name: "Build Latest nightly"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      fake_updates:
        description: "Force build. Run the workflow as if there were new commits to the upstream."
        type: boolean
        default: false
      sync_test_mode:
        description: 'Fork Sync Test Mode'
        type: boolean
        default: false

env:
  YAAGL_NIGHTLY: true
  YAAGL_NIGHTLY_SUFFIX: "Nightly"
permissions:
  contents: "write"
  packages: "write"
  pull-requests: "read"
jobs:
  check_updates:
    runs-on: macos-latest
    outputs:
      has_new_commits: ${{ steps.sync.outputs.has_new_commits }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Sync upstream changes
        id: sync
        uses: kurorinchan/Fork-Sync-With-Upstream-action@main
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: yaagl/yet-another-anime-game-launcher
          upstream_sync_branch: main
  
          # Set test_mode true during manual dispatch to run tests instead of the true action!!
          test_mode: ${{ inputs.sync_test_mode }}
          
      - name: Show value of 'has_new_commits'
        run: echo ${{ steps.sync.outputs.has_new_commits }}

      - name: New commits found
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found to sync."
      
      - name: No new commits
        if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "There were no new commits."

  build:
    runs-on: macos-latest
    needs: check_updates
    if: needs.check_updates.outputs.has_new_commits == 'true' || inputs.fake_updates == 'true'
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        env:
          YAAGL_VERSION: ${{ steps.date.outputs.date }}-nightly
        run: |
          ./configure.sh
          YAAGL_CHANNEL_CLIENT=hk4ecn node ./build-app.js
          cp dist/Yaagl/resources.neu resources_hk4ecn.neu
          YAAGL_CHANNEL_CLIENT=hk4eos node ./build-app.js
          cp dist/Yaagl/resources.neu resources_hk4eos.neu 
          YAAGL_CHANNEL_CLIENT=bh3glb node ./build-app.js
          cp dist/Yaagl/resources.neu resources_bh3glb.neu
          YAAGL_CHANNEL_CLIENT=hkrpgcn node ./build-app.js
          cp dist/Yaagl/resources.neu resources_hkrpgcn.neu
          YAAGL_CHANNEL_CLIENT=hkrpgos node ./build-app.js
          cp dist/Yaagl/resources.neu resources_hkrpgos.neu
          YAAGL_CHANNEL_CLIENT=napcn node ./build-app.js
          cp dist/Yaagl/resources.neu resources_napcn.neu
          YAAGL_CHANNEL_CLIENT=napos node ./build-app.js
          cp dist/Yaagl/resources.neu resources_napos.neu

      - name: Tar app
        run: |
          tar -zcf "Yaagl ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz" "Yaagl ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app"
          tar -zcf "Yaagl OS ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz" "Yaagl OS ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app"
          tar -zcf "Yaagl Honkai Global ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz" "Yaagl Honkai Global ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app"
          tar -zcf "Yaagl HSR ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz" "Yaagl HSR ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app"
          tar -zcf "Yaagl HSR OS ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz" "Yaagl HSR OS ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app"
          tar -zcf "Yaagl ZZZ ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz" "Yaagl ZZZ ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app"
          tar -zcf "Yaagl ZZZ OS ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz" "Yaagl ZZZ OS ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app"
      - name: Generate prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          title: "${{ steps.date.outputs.date }}-nightly"
          automatic_release_tag: ${{ steps.date.outputs.date }}-nightly
          files: |
            Yaagl ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz
            Yaagl OS ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz
            Yaagl Honkai Global ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz
            Yaagl HSR ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz
            Yaagl HSR OS ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz
            Yaagl ZZZ ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz
            Yaagl ZZZ OS ${{ env.YAAGL_NIGHTLY_SUFFIX }}.app.tar.gz
            resources_hk4ecn.neu
            resources_hk4eos.neu
            resources_bh3glb.neu
            resources_hkrpgcn.neu
            resources_hkrpgos.neu
            resources_napcn.neu
            resources_napos.neu
